### ISSUE TITLE
Pinging for specific players hitting snitches

### ISSUE THREAD

**Issue by Gjum** [Maxopoly/Kira#1]
The straightforward way is to set `everyoneformat` to `PLAYER1|PLAYER2`. But this removes the player name from the alert.

Instead, the `@everyone`/`@here` should be appended to the alert, or inserted at the location of a variable (configurable in format template).

**Comment by Maxopoly** [comment]
`%PING%` is already a thing and will be replaced with the highest priority ping contained in the message. I think simply adding a boolean `pingsReplaceText` which would allow players to not have pings replace text, but still appear in `%PING%` would be enough to solve this issue.

Do you agree?

**Comment by Gjum** [comment]
`pingsReplaceText` would solve my use case. :+1: Do you agree it'd make sense to make it default to `false` and, if there's no `%PING%` template, appending a ping to the output anyway?

And thanks for pointing out `%PING%`, I wasn't aware of that as it doesn't appear in [the docs](https://github.com/Maxopoly/Kira/wiki/Relays).

**Comment by Maxopoly** [comment]
I think defaulting it to false for future configs is good, but only if that also includes %PING% being included in the default chat and snitch syntax. I will adjust both the already existing default relay config and relays configs created in the future to be this way.

For preexisting custom setups it should be set to true though, because these setups are most likely not aware of `%PING%` and `pingsReplaceText` being set to false by default would effectively disable their pinging capability.

Pings shouldn't appear if the syntax doesn't include them though. I will however include a warning if a config setting is changed and puts the relay config in the state of: pingsReplaceText is set to false, %PING% is not included in the chat/snitch syntax and `pingsEnabled` is set to true

I will also add `%PING%` to the wiki.

**Comment by Maxopoly** [comment]
Actually thinking about it more @Gjum , do you think there are valid use cases for having `pingReplaceText` set to true (disregarding legacy configs)? I can't think of any and think it might be better to just never replace, but only use `%PING%`

**Comment by Gjum** [comment]
Maybe some odd use cases requiring removal of verbose or sensitive info with obfuscated/minified regexes. Nothing else comes to mind that would really need to be supported. IMO simple and predictable usage wins here, especially if it simplifies the [logic](https://pbs.twimg.com/media/C6ROe0mU0AEmpzz.jpg).

**Comment by Maxopoly** [comment]
Should be fixed with https://github.com/Maxopoly/Kira/commit/95a1d8d56072a60d1363dc4fb18cd3e2ca92445c and https://github.com/Maxopoly/Kira/commit/d6eedb9c3fb8594bd5729aac56ae8108ec476af9. I'll deploy it later today.
